### ISSUE TITLE
Immutable object

### ISSUE THREAD

**Issue by dakolech** [briisk/briisk-javascript#1]
Don't mutate objects. Why? Because it is hard to watch changes in objects, you can change some attribute in one part of the application, but the other part won't know if something changes there. Also, frameworks like Angular, React, AngularJS will update the view faster (checking reference of the object is faster than iterating over all array items, object attributes). 

**Arrays:**
- `push` method is forbidden, use `concat` instead
- `splice` method is forbidden, use `slice` instead if you have index or use `filter`
- `shift`, `pop` and `unshift` are forbidden, use `slice` and `concat`

```

const someArray = [1, 2, 3];

// bad
someArray.push(4);
// good
const newArray = someArray.concat(4);

// bad
someArray.splice(2,1);
// good
const newArray = someArray.slice(0,2);
const anotherArray = someArray.filter(item => item !== 3);

// bad
someArray.shift();
// good
const newArray = someArray.slice(1, someArray.length);

// bad
someArray.pop();
// good
const newArray = someArray.slice(0, someArray.length - 1);

// bad
someArray.unshift(0);
// good
const newArray = [0].concat(someArray);
```

**Objects:**
- don't modify attributes directly, use `Object.assign` with an empty object as a first argument or spread operator

```
const someObject = {
  attr: 123,
  attr2: 'asd',
};

// bad
someObject.attr = 456;
// good
const newObject = Object.assign({}, someObject, { attr: 456 } );
const anotherObject = {
  ...someObject,
  attr: 456,
};
```

It will affect 4.2, a little bit 11.1

**Comment by franciscotln** [comment]
`Object.assign()` or the object spread operator only work the way you described if there is no nested object. If we don't want to mutate objects (including nested ones) we should write our own implementation like [R.clone](http://ramdajs.com/docs/#clone)

**Comment by dakolech** [comment]
First scenario, modifying an attribute that is not in the nested object:
```
const bigObject = {
  nestedOne: {
    nestedAttr: 123,
  },
  nestedTwo: {
    nestedAttr: 123,
  },
  simpleAttr: 345,
};

const newBigObject = {
  ...bigObject,
  simpleAttr: 678,
}
```
In that case, `bigObject.nestedOne` hasn't changed, so if somebody would observe that one it shouldn't be informed about changes. Immutable and Ramda are working in this way:
```
const newObject = R.assoc('simpleAttr', 567, bigObject);
newObject.nestedOne === bigObject.nestedOne; // true
```
If all nested objects would change, then it would trigger all digest/detections loops across the whole application, which is not good for performance.

The second scenario, modifying an attribute that is in nested object:
```
const bigObject = {
  nestedOne: {
    nestedAttr: 123,
  },
  nestedTwo: {
    nestedAttr: 123,
  },
  simpleAttr: 345,
};

const newBigObject = {
  ...bigObject,
  nestedOne: {
    ...bigObject.nestedOne,
    anotherAtrr: 432,
  }
}
```
In that case, `bigObject.nestedOne` has changed, so if somebody would observe that one it should be informed about changes. You should only change references of the changed objects.
