### ISSUE TITLE
Add spaces inside brackets

### ISSUE THREAD

**Issue by dakolech** [briisk/briisk-javascript#11]
Rule [18.10 ](https://github.com/briisk/briisk-javascript#whitespace--in-brackets) Do not add spaces inside brackets.
In my opinion, we should allow adding spaces inside brackets, for example, providers in Angular.

**Comment by augkamil** [comment]
Is there any other reason then Angular providers for that? The perfect solution for this would be to allow the spaces only in case of providers but it's not doable now. And I don't want to have things like ```const foo = [ 1, 2, 3 ]; console.log(foo[ 0 ]);``` in the code.
With providers you can start with adding them in a new line instead:
```
providers: [
  MyProvider1,
  MyProvider2
]
```

**Comment by dakolech** [comment]
IMO `const foo = [ 1, 2, 3 ];` is more readable than `const foo = [1, 2, 3];`, it's the same situationwith the object: `const foo = { attr: 123 };` vs `const foo = {attr: 123};`. But I can agree that referring to object attributes should be avoided with spaces (`foo[ 0 ]`). In this case there is [computed-property-spacing](http://eslint.org/docs/rules/computed-property-spacing) rule

**Comment by augkamil** [comment]
so if we add ```computed-property-spacing``` then we can remove 18.10
