### ISSUE TITLE
Avoid having lines of code that are longer than 120 characters 

### ISSUE THREAD

**Issue by dakolech** [briisk/briisk-javascript#12]
Rule [18.12](https://github.com/briisk/briisk-javascript#whitespace--max-len) Avoid having lines of code that are longer than 100 characters (including whitespace).
We are using 120 characters, right?

**Comment by augkamil** [comment]
120 characters for a regular screen is ok

**Comment by mikoSTAR** [comment]
Currently I have 120 as well
