### ISSUE TITLE
TypeScript: interface/types naming

### ISSUE THREAD

**Issue by dakolech** [briisk/briisk-javascript#16]
We should choose the naming convention for interfaces and types:

1. ❤️ 
```
interface User {
  name: string;
}
type Product = {
  name: string;
}
```

2. 🎉 
```
interface IUser {
  name: string;
}
type TProduct = {
  name: string;
}
```

3. 😄 
```
interface UserI {
  name: string;
}
type ProductT = {
  name: string;
}
```

The first one will interrupt with class names. But with functional style (`function createUser() {...}`), this would not happen. I prefer the first one.

**Comment by franciscotln** [comment]
I think that the first option is cleaner

**Comment by miroslaw-bogacz** [comment]
@franciscotln how do you make User class when do you use User name on the interface?

**Comment by dakolech** [comment]
@miroslaw-bogacz you don't create User class :) 
We can create:
```
function createUser(attrs): User {
  return {
     name: attrs.name,
     fullName() {
       return this.name;
     }
  }
}
```
The outpu will be the same as you would use class here.

**Comment by miroslaw-bogacz** [comment]
better is 

```
class User implements IUser {

}
```

**Comment by dakolech** [comment]
Why?

**Comment by miroslaw-bogacz** [comment]
because I can create User class :)

**Comment by franciscotln** [comment]
do you have any real case where you need to create a class User ? :D I think interfaces are really good for declaring data structure, it makes easier to work for example with VS code and avoid typos etc. I wouldn't use an interface to imitate a class structure with methods etc, instead I'd rather create the class itself
```
interface User {
  id: number;
  name: string;
  age: number;
}

// some use case
fetchUserFromAPI(): User { ... }
```
