### ISSUE TITLE
Ternary operator multiline

### ISSUE THREAD

**Issue by dakolech** [briisk/briisk-javascript#2]
1. ❤️ 
```
someStatement ?
  value1 :
  value2;
```

2. 🎉 
```
someStatement ?
value1
:
value2;
```

3. 😄 
```
someStatement
? value1
: value2;
```

We need to choose one style. I prefer the first one.

**Comment by przemkow** [comment]
2nd one is horrible, 
+1 for 1st and 3rd

**Comment by lisek02** [comment]
first

**Comment by mikoSTAR** [comment]
2nd one is horrible and 1st is terrible
3rd is sweet :D

**Comment by augkamil** [comment]
@99four @aresimo what do you choose?
