### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by dakolech** [briisk/briisk-javascript#3]
Some rules for testing in JavaScript:

- Test only public functions/methods. Don't export variables/functions/objects or make public methods only for testing. You are not using them in the application directly, so you don't need to tests them directly.
- Unit testing - Component is a unit (with all logic and template, you shouldn't test logic without template), Service is a unit, Function is a unit. So you are writing unit tests when you are testing only one unit and you are mocking all dependecies, parameters.
- Integration testing - you are writing integration tests when you are testing more than one unit.
- Use `beforeAll` instead of `beforeEach` if possible. Tests will execute faster because `beforeAll` will run only once.
- always check arguments of called spies (`toHaveBeenCalledWith`) if there are any

**Comment by mikoSTAR** [comment]
It's harder to maintain and read code once you use `beforeAll` instead of `beforeEach`.
Somebody wrote that in test you don't need to be as DRY as possible

**Comment by dakolech** [comment]
@mikoSTAR It's not harder when you know how it works. Of course, sometimes you need to clear tested thing before each test, but not always. For example, you should compile component once if you are checking some visuals only.
