### ISSUE TITLE
project configuration file

### ISSUE THREAD

**Issue by przemkow** [briisk/briisk-javascript#31]
We need to find a common pattern for storing configurations file in Briisk projects for Ionic, AngularJS, Angular2, React, React-Native apps.
I would suggest keeping standard provided with Angular CLI: `src/environments/` for all applications. 
Could we check for instance on blog app if keeping this pattern would be possible for our requirements?

**Comment by franciscotln** [comment]
If it is possible to use one pattern for all kinds of project (ionic, react native, nativeScript?, plain ng4) then it's fine.

**Comment by augkamil** [comment]
@przemkow add a PR with this good practice. Add in every framework (eg. Angular, AngularJS, React) a line with this pattern.

**Comment by augkamil** [comment]
closed with https://github.com/briisk/briisk-javascript/pull/32
