### ISSUE TITLE
Scripts in package.json

### ISSUE THREAD

**Issue by dakolech** [briisk/briisk-javascript#33]
There should be some core scripts in every package.json.

**npm run init** - to initialize application, should be run once after git clone
**npm start** - to start application, should run application in the development mode
**npm run build** - to build application, should build application in the production mode
**npm test** - to test application, should run test with watch flag and in the continuous mode
**npm run test:ci** - to test application, should run test without watch flag and in the single run mode
**npm run lint** - to lint application, should run all linters once

**Comment by przemkow** [comment]
for web applications it seems enough, however for mobiles I would extend it with:
`npm run start:ios`
`npm run start:android`
`npm run build:ios`
`npm run build:android`

**Comment by mikoSTAR** [comment]
Sometimes you want to build with different config. I would add as well:
```
npm run build:ios --env=production
npm run build:ios --env=staging
npm run build:android --env=production
npm run build:android --env=staging
```

**Comment by dakolech** [comment]
@mikoSTAR should be `npm run build:ios -- --env=production` but I think that we can do something like this:

```
npm run build:ios:prod
npm run build:ios:staging
npm run build:android:prod
npm run build:android:staging
```
