### ISSUE TITLE
Functions instead of methods

### ISSUE THREAD

**Issue by dakolech** [briisk/briisk-javascript#5]
If the method is not manipulating an instance of a class (if there is no `this` keyword in the method) then this is a function that should be outside of the class. Why? Because this method is not operating on the object, it's independent. It will be possible to use it in other places of the application. Also, if it is a public function, testing will be easier.

```
// bad
class SomeClass {
  addItem(arr, item) {
    return arr.concat(item);
  }
 ...
}

// good 
class SomeClass {
 ...
}

function addItem(arr, item) {
  return arr.concat(item);
}
```

**Comment by augkamil** [comment]
I woulda add to this definition that if the method is not manipulating an instance of a class then this is a function that should be outside of the class.
