### ISSUE TITLE
Array prototype methods

### ISSUE THREAD

**Issue by dakolech** [briisk/briisk-javascript#6]
**filter**
Use this method for removing items from the array

**map**
Use this method for modifying items in the array. You can modify one or more. Also, you can return different items depending on actual, but the size of the array will be the same.

**reduce, reduceRight**
Use this method for generating different structures: strings, objects, arrays with different number of items

**find**
Use this method, if you want exactly one item from the array. If you want more than one, use `filter`.

**every**
Use this method, if you want to check that all items in the array pass the test provided by the function.

**some**
Use this method, if you want to check that at least one item in the array pass the test provided by the function.

**concat**
Use this method, if you want to add an item to the array or you want to merge two arrays.

**fill**
Use this method, if you want to set values for the array. Use this method instead of `map` if value is static.

**forEach**
Use this method, if you to trigger side effect. For example calling some action, triggering an event. Don't use it for modifying array.

**inlcudes**
Use this method, if you want to check if at least one array includes given argument.

**slice**
Use this method, if you want remove item/items from the array and you know the index. If you don't know the index, use `filter`.

**join**
Use this method, if you want to join all items into one string.

**reverse**
Use this method, if you want to reverse the order of items in the array, but only with a `slice() `or spread operator `const REVERSED = [...myArray].reverse()` because it mutates the original array.

**sort**
Use this method, if you want to sort items in the array, but only with a `slice() `or spread operator `const SORTED = [...myArray].reverse()` because it mutates the original array.

Other methods should be forbidden in my opinion.

**Comment by augkamil** [comment]
We can restrict the methods to those listed here

**Comment by franciscotln** [comment]
don't use reverse if it's not preceded by slice() or spread operator `const REVERSED =
 [...myArray].reverse()` because it mutates the original array.

**Comment by dakolech** [comment]
Updated

**Comment by dakolech** [comment]
Added sort method
