### ISSUE TITLE
Leading underscore before private methods and attributes

### ISSUE THREAD

**Issue by dakolech** [briisk/briisk-javascript#8]
[22.4](https://github.com/briisk/briisk-javascript#naming--leading-underscore) I think that we should use underscore before private methods when writing in JavaScript, and avoid them when writing in TypeScript. 
There was a discussion about it and I think that we are clear with this one.

**Comment by augkamil** [comment]
I agree with this rule in TypeScript, but why should we name methods in JavaScript like ```_someHelperCalculation()``` instead of naming it ```someHelperCalculation()``` it's an additional character and the name should be enough to know the purpose of the method.

**Comment by dakolech** [comment]
Sometimes the name doesn't describe if it should be used outside of the class. `getUser(id)` can be used as an internal method or as a public one. If we will use leading underscore, both developers and reviews will know from the beginning for where this method should be used, without checking it's implementation.

**Comment by augkamil** [comment]
ok, this is a better argument 👍
