### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by dakolech** [briisk/briisk-javascript#9]
Don't inherit from more than one class. Why? Because it is hard to maintain this kind of objects, you need to search through more than two classes where attributes and methods come from. Create functions instead if possible

```
// bad 
class Class1 {
...
method1() {..};
}

class Class2 extends Class1 {
...
}

class Class3 extends Class2 {
...
  method2() {
    this.method1();
  }
}

// good
function method1() {..};

class Class2  {
...
}

class Class3 extends Class2 {
...
  method2() {
    method1();
  }
}
```

**Comment by augkamil** [comment]
I would also add that inheritance should be used with great care. It is really hard in maintenance.

**Comment by franciscotln** [comment]
The same should apply for inheritance when writing typescript interfaces
